### ISSUE TITLE
Suggestions for the 'News Services' section

### ISSUE THREAD

**Issue by briatte** [abhishekbanthia/Public-APIs#111]
The News APIs currently lists only NewsAPI.org (which looks truly awesome) and The Guardian. You might also want to list a few other titles, e.g.:

* New York Times: https://developer.nytimes.com/
* Washington Post: https://newsapi.org/the-washington-post-api
* BBC (incl. BBC News): https://developer.bbc.co.uk/content/bbc-platform-api
* Associated Press: https://developer.ap.org/ap-content-api
* Financial Times: https://developer.ft.com/

**Comment by abhishekbanthia** [comment]
Thanks for the suggestion. If you'd like to add them, send me a PR; I'd happily approve it.

**Comment by cockmeat** [comment]
Cancel whatever I have here and stop messaging me - i didn't  sign up for any charges and are u guys charging my credit card?
