### ISSUE TITLE
Create a webpage of readme file

### ISSUE THREAD

**Issue by jsroyal** [abhishekbanthia/Public-APIs#118]
It will be also helpful if we create GitHub static web page of the readme file and provide a link to it in the header of repo and readme file.Also, share the link with social media.More people can reach out.

**Comment by abhishekbanthia** [comment]
That's an interesting idea, @jsroyal. To be honest, I'm not much familiar with web-dev or hosting sites through GitHub but If you'd like to go ahead and create something, please do so 💯

**Comment by jsroyal** [comment]
@abhishekbanthia  Thanks for appreciating.This repo has very good contents so Why not more user reach out without even GitHub.
Sure! I will do it and send you a PR.
