### ISSUE TITLE
Is there any Movies Subtitles API?

### ISSUE THREAD

**Issue by qadirsuh** [abhishekbanthia/Public-APIs#134]
Abstract: I have created a bot and there is a chat interface between user and bot, via chat interface user can say Play Pulp Fiction {{name}} from the scene Ezekiel 25:17
20s later the movie shall be played starting at the scene which the user requested. In this case this would be:
https://www.youtube.com/watch?v=3PeyiU3uWJ8&feature=youtu.be&t=2m33s

What I am trying to achieve is.

- Find a database of movies with all subtitles/lyrics/texts
- Index all lyrics in our own database (or if there is a API from a 3rd party service, even better)
- Create a REST endpoint (new nodejs module) to search/stream movies in this manner

Is there any kind of Database and/or api. please paste here.

**Comment by abhishekbanthia** [comment]
Currently, I haven't come across an API matching your requirements.
