### ISSUE TITLE
Add ‘The SMS Works’ to the Communications category

### ISSUE THREAD

**Issue by phil-warner** [abhishekbanthia/Public-APIs#189]
- [The SMS Works](https://thesmsworks.co.uk/) - The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.

**Comment by abhishekbanthia** [comment]
Looks like a great addition. Please send me a PR.

**Comment by phil-warner** [comment]
Hi Abhishek

I've cloned the repo but I'm unable to create a PR from my branch. It's
says that I don't have permission. What am I doing wrong?

Regards, Phil

**Comment by abhishekbanthia** [comment]
Phil, you need to fork the repo instead of cloning.
