### ISSUE TITLE
Need help sorting the APIs

### ISSUE THREAD

**Issue by abhishekbanthia** [abhishekbanthia/Public-APIs#75]
Hi guys, I'll like to get the APIs in shape by sorting them alphabetically. This will help make searching and reading the file straightforward and elementary. Let me know if anybody wants to volunteer; and I'll add them as a collaborator for the repo.

Thanks.

**Comment by irshadpc** [comment]
Let me try to do.

**Comment by abhishekbanthia** [comment]
Closing as #81 sorted the APIs.
