### ISSUE TITLE
Found a new API for Quotes: Need a new section in Table of Content

### ISSUE THREAD

**Issue by aps120797** [abhishekbanthia/Public-APIs#98]
@abhishekbanthia  Here are links for **Quotes on Design API** to retrieve **_wonderful Quotes_**:

- The API V4.0: https://quotesondesign.com/api-v4-0/

- API V3.0: https://quotesondesign.com/the-api/

**Comment by abhishekbanthia** [comment]
That's looks great. You can go ahead and add this and send me a PR. 💯
